name: Go MultiPlat Binary

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
          # - goos: windows
          #   goarch: amd64
          # - goos: darwin
          #   goarch: arm
          # - goos: darwin
          #   goarch: amd64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Get version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/')

    - name: Build
      run: |
        VERSION=${{ env.VERSION || 'dev' }}
        OUTPUT_NAME="k8shc-${{ matrix.goos }}-${{ matrix.goarch }}"
        [ "${{ matrix.goos }}" = "windows" ] && OUTPUT_NAME="${OUTPUT_NAME}.exe"
        
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -ldflags "-X main.version=$VERSION" -o bin/${OUTPUT_NAME} .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: k8shc-${{ matrix.goos }}-${{ matrix.goarch }}
        path: bin/
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: bin/*
      if: startsWith(github.ref, 'refs/tags/')
